name: Maven Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/AED/Springboot/Peliculas # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B clean package --file Peliculas/pom.xml

    - name: subir fichero
      uses: actions/upload-artifact@v4
      with:
        name: allartifacts
        path: Peliculas/target/*

